
#ifndef XL_DBUS_H
#define XL_DBUS_H

/* Introspection data for the service we are exporting */
static const gchar introspection_xml[] =
  "<node>"
  "  <interface name='org.xen.xl.Argv'>"
/* DOMAIN SUBCOMMANDS */
  "    <method name='create'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='config-update'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='console'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='destroy'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='domid'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='domname'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='rename'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='dump-core'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='mem-set'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='mem-max'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='migrate'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='remus'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='pause'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='reboot'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='restore'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='save'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='sharing'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='shutdown'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='sysrq'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='trigger'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='unpause'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vcpu-set'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vcpu-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vcpu-pin'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vm-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*
  "    <method name='vncviewer'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
*/
/* XEN HOST SUBCOMMANDS */
  "    <method name='debug-keys'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='set-parameters'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='info'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='top'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='uptime'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='claims'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/* SCHEDULER SUBCOMMANDS */
  "    <method name='sched-credit'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='sched-credit2'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='sched-rtds'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/* CPUPOOLS COMMANDS */
  "    <method name='cpupool-create'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cpupool-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cpupool-destroy'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cpupool-rename'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cpupool-cpu-add'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cpupool-cpu-remove'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cpupool-migrate'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cpupool-numa-split'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/* VIRTUAL DEVICE COMMANDS */
/*   BLOCK DEVICES */
  "    <method name='block-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='block-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='block-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cd-insert'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='cd-eject'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   NETWORK DEVICES */
  "    <method name='network-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='network-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='network-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   CHANNEL DEVICES */
  "    <method name='channel-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   VIRTUAL TRUSTED PLATFORM MODULE (vTPM) DEVICES */
  "    <method name='vtpm-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vtpm-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vtpm-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   VDISPL DEVICES */
  "    <method name='vdispl-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vdispl-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vdispl-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   VSND DEVICES */
  "    <method name='vsnd-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vsnd-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vsnd-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   KEYBOARD DEVICES */
  "    <method name='vkb-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vkb-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='vkb-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   PCI PASS-THROUGH */
  "    <method name='pci-assignable-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='pci-assignable-add'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='pci-assignable-remove'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='pci-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='pci-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='pci-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   USB PASS-THROUGH */
  "    <method name='usbctrl-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='usbctrl-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='usbdev-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='usbdev-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='usb-list'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/* DEVICE-MODEL CONTROL */
  "    <method name='qemu-monitor-command'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/* FLASK */
  "    <method name='getenforce'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='setenforce'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='loadpolicy'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/* PLATFORM SHARED RESOURCE MONITORING/CONTROL */
  "    <method name='psr-hwinfo'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   CACHE MONITORING TECHNOLOGY */
  "    <method name='psr-cmt-attach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='psr-cmt-detach'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='psr-cmt-show'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   CACHE ALLOCATION TECHNOLOGY */
  "    <method name='psr-cat-set'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='psr-cat-show'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
/*   Memory Bandwidth Allocation */
  "    <method name='psr-mba-set'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "    <method name='psr-mba-show'>"
  "      <annotation name='org.gtk.GDBus.Annotation' value='OnMethod'/>"
  "      <arg type='s' name='args' direction='in'/>"
  "      <arg type='h' name='response' direction='out'/>"
  "    </method>"
  "  </interface>"
  "</node>";

#endif
